runtime: php55
api_version: 1
threadsafe: false

handlers:
- url: /
  script: www/index.php
  
-   url: /css  #your css folder
    static_dir: www/css 

-   url: /js #your javascript folder
    static_dir: www/js

-   url: /images #your javascript folder
    static_dir: www/images
    
 
    
