 runtime: php55
 api_version: 1
 threadsafe: false

 handlers:
 - url: /
   static_files: www/index.php
   upload: www/index.php

 - url: /(.*)
   static_files: www/\1
   upload: www/(.*)
